# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/willsnew/cmake-3.7.0-rc3-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/willsnew/cmake-3.7.0-rc3-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/willsnew/桌面/RISC-V-sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/willsnew/桌面/RISC-V-sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/willsnew/cmake-3.7.0-rc3-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/willsnew/cmake-3.7.0-rc3-Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/willsnew/桌面/RISC-V-sim/CMakeFiles /home/willsnew/桌面/RISC-V-sim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/willsnew/桌面/RISC-V-sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named riscv_sim

# Build rule for target.
riscv_sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 riscv_sim
.PHONY : riscv_sim

# fast build rule for target.
riscv_sim/fast:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/build
.PHONY : riscv_sim/fast

decode.o: decode.cpp.o

.PHONY : decode.o

# target to build an object file
decode.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/decode.cpp.o
.PHONY : decode.cpp.o

decode.i: decode.cpp.i

.PHONY : decode.i

# target to preprocess a source file
decode.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/decode.cpp.i
.PHONY : decode.cpp.i

decode.s: decode.cpp.s

.PHONY : decode.s

# target to generate assembly for a file
decode.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/decode.cpp.s
.PHONY : decode.cpp.s

elf.o: elf.cpp.o

.PHONY : elf.o

# target to build an object file
elf.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/elf.cpp.o
.PHONY : elf.cpp.o

elf.i: elf.cpp.i

.PHONY : elf.i

# target to preprocess a source file
elf.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/elf.cpp.i
.PHONY : elf.cpp.i

elf.s: elf.cpp.s

.PHONY : elf.s

# target to generate assembly for a file
elf.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/elf.cpp.s
.PHONY : elf.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/main.cpp.s
.PHONY : main.cpp.s

vmm.o: vmm.cpp.o

.PHONY : vmm.o

# target to build an object file
vmm.cpp.o:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/vmm.cpp.o
.PHONY : vmm.cpp.o

vmm.i: vmm.cpp.i

.PHONY : vmm.i

# target to preprocess a source file
vmm.cpp.i:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/vmm.cpp.i
.PHONY : vmm.cpp.i

vmm.s: vmm.cpp.s

.PHONY : vmm.s

# target to generate assembly for a file
vmm.cpp.s:
	$(MAKE) -f CMakeFiles/riscv_sim.dir/build.make CMakeFiles/riscv_sim.dir/vmm.cpp.s
.PHONY : vmm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... riscv_sim"
	@echo "... decode.o"
	@echo "... decode.i"
	@echo "... decode.s"
	@echo "... elf.o"
	@echo "... elf.i"
	@echo "... elf.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... vmm.o"
	@echo "... vmm.i"
	@echo "... vmm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

